import os
import sys
import argparse
import numpy as np
import cv2
import torch
import shutil

# This script serves as the Proof of Concept for chaining SAM 2 and MatAnyone 2.

def extract_frames(video_path, output_dir):
    print(f"Extracting frames from {video_path} to {output_dir}")
    os.makedirs(output_dir, exist_ok=True)
    cap = cv2.VideoCapture(video_path)
    frame_idx = 0
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        frame_path = os.path.join(output_dir, f"{frame_idx:05d}.jpg")
        cv2.imwrite(frame_path, frame)
        frame_idx += 1
    cap.release()
    print(f"Extracted {frame_idx} frames.")
    return frame_idx

def run_sam2_tracking(frames_dir, output_mask_dir, init_point, checkpoint_dir):
    print(f"Running SAM 2.1 tracking starting with point {init_point}...")
    os.makedirs(output_mask_dir, exist_ok=True)
    
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    sam2_dir = os.path.join(repo_root, "backend", "third_party", "segment-anything-2")
    if sam2_dir not in sys.path:
        sys.path.insert(0, sam2_dir)
        
    from sam2.build_sam import build_sam2_video_predictor
    
    # Initialize predictor
    model_cfg = "configs/sam2.1/sam2.1_hiera_t.yaml"
    sam2_checkpoint = os.path.join(checkpoint_dir, "sam2.1_hiera_tiny.pt")
    
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    predictor = build_sam2_video_predictor(model_cfg, sam2_checkpoint, device=device)
    
    # Init state
    inference_state = predictor.init_state(video_path=frames_dir)
    
    # Add click point on frame 0
    # point = np.array([x, y]), label = 1 (positive click)
    points = np.array([[init_point[0], init_point[1]]], dtype=np.float32)
    labels = np.array([1], dtype=np.int32)
    
    _, out_obj_ids, out_mask_logits = predictor.add_new_points_or_box(
        inference_state=inference_state,
        frame_idx=0,
        obj_id=1,
        points=points,
        labels=labels,
    )
    
    # Propagate through video
    print("Propagating SAM 2.1 masks over all frames...")
    frames = sorted(os.listdir(frames_dir))
    for out_frame_idx, out_obj_ids, out_mask_logits in predictor.propagate_in_video(inference_state):
        mask = (out_mask_logits[0] > 0.0).cpu().numpy().squeeze().astype(np.uint8) * 255
        frame_name = frames[out_frame_idx].replace('.jpg', '.png')
        cv2.imwrite(os.path.join(output_mask_dir, frame_name), mask)
        
    print(f"SAM 2.1 tracking completed. Masks saved to {output_mask_dir}")

def run_matanyone2(video_path, frames_dir, masks_dir, output_alpha_dir, checkpoint_dir):
    print("Running MatAnyone 2 for alpha refinement...")
    os.makedirs(output_alpha_dir, exist_ok=True)
    
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    matanyone2_dir = os.path.join(repo_root, "backend", "third_party", "MatAnyone2")
    if matanyone2_dir not in sys.path:
        sys.path.insert(0, matanyone2_dir)
        
    import torch
    from inference_matanyone2 import main as matanyone2_inference
    
    matanyone2_checkpoint = os.path.join(checkpoint_dir, "matanyone2.pth")
    
    # The first mask generated by SAM2 acts as the initial target for MatAnyone2
    first_mask_path = os.path.join(masks_dir, "00000.png")
    
    print("Starting MatAnyone 2 process...")
    # This automatically processes the video and outputs to output_alpha_dir
    matanyone2_inference(
        input_path=frames_dir,  # Pass frames_dir instead of video to bypass torchvision.io.read_video
        mask_path=first_mask_path,
        output_path=output_alpha_dir,
        ckpt_path=matanyone2_checkpoint,
        save_image=True,
        max_size=512
    )
    print(f"MatAnyone 2 refinement completed. Results saved to {output_alpha_dir}")

def compile_video(frames_dir, alpha_dir, output_video):
    print(f"Compiling final transparent video to {output_video}")
    import ffmpeg
    
    # Get the image sequence from MatAnyone's output if it outputs sequence, 
    # or if it outputs video, we might not need to compile manually.
    # MatAnyone2 process_video actually outputs video by default. 
    # Let's check if the output is already a video.
    
    print("Compilation handled directly or skip for now if already built by MatAnyone.")

def main():
    parser = argparse.ArgumentParser(description="RotoFox - Smart Video Segmentation PoC Pipeline")
    parser.add_argument("--video", type=str, required=True, help="Path to input video")
    parser.add_argument("--out", type=str, default="output.mov", help="Path to output video")
    parser.add_argument("--x", type=int, required=True, help="X coordinate for initial click")
    parser.add_argument("--y", type=int, required=True, help="Y coordinate for initial click")
    args = parser.parse_args()

    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    workspace = os.path.join(repo_root, "backend", "cache_workspace")
    checkpoint_dir = os.path.join(repo_root, "backend", "checkpoints")
    
    frames_dir = os.path.join(workspace, "frames")
    masks_dir = os.path.join(workspace, "masks")
    alphas_dir = os.path.join(workspace, "alphas")

    # 1. Extract Frames
    extract_frames(args.video, frames_dir)
    
    # 2. SAM 2 Tracking (Already completed successfully, skipping to save time)
    # run_sam2_tracking(frames_dir, masks_dir, (args.x, args.y), checkpoint_dir)
    
    # 3. MatAnyone 2 Refinement
    run_matanyone2(args.video, frames_dir, masks_dir, alphas_dir, checkpoint_dir)
    
if __name__ == "__main__":
    main()
